export { default as Movies } from "./movies/Movies";
export { default as MovieInformation } from "./movie Information/MovieInformation";
export { default as Navbar } from "./navbar/Navbar";
export { default as Actors } from "./actors/actors";
export { default as Profile } from "./profile/Profile";
export { default as Sidebar } from "./sidebar/Sidebar";
export { default as MovieList } from "./MovieList/MovieList";
export { default as Movie } from "./Movie/Movie";
export { default as Search } from "./search/Search";
export { default as Pagination } from "./pagination/Pagination";
export { default as RatedCards } from "./RatedCards/RatedCards";
export { default as FeaturedMovie } from "./FeaturedMovie/FeaturedMovie";
